### ISSUE TITLE
Readme Powa

### ISSUE THREAD

**Issue by zaneck** [arctarus44/pac-tp3#1]
Just use : 
" - [ ]" or " - [X]' to do a to do list

And please just say "Avec plein de trucs super qui ressemblent presque à des maths"

=)

Enjoy, I will help you!

**Comment by arctarus44** [comment]
Thank you for your comments.

I agree with your comment on the readme.

Sadly, I think math are not something "super" as you suggest. In my opinion, teaching math must be prohibited. Thus, we can use this freed time for teaching some usefull topic, like Doctor Who, or how to create locats.

**Comment by zaneck** [comment]
What a locats?

Doctor Who? are your British?

**Comment by arctarus44** [comment]
A locats is a specific kind of lolcats with short legs cats.

I'am not british, worse than that. I come from a country rules by cheese and frog.
Did you any comment on the description of this repository?
